### ISSUE TITLE
XrmClient is failing since 13-July-2022

### ISSUE THREAD

**Issue by rtmaus** [AymericM78/PowerDataOps#5]
We are using the XrmClient as part of our github actions. 

We are now receiving the following error in our 
PowerDataOps version = 1.0.0.99
AuthType=ClientSecret;Url=[https://******.crm6.dynamics.com;ClientId=***;ClientSecret=***;](https://******.crm6.dynamics.com%3Bclientid%3D%2A%2A%2A%3Bclientsecret%3D%2A%2A%2A%3B/)
Get-CrmConnection : Method not found: 'Void 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient.set_EnableDeprecatedOnLineWSTrustFlow(Boolean)'.
At C:\Users\runneradmin\Documents\WindowsPowerShell\Modules\PowerDataOps\1.0.0.99\src\Client\New-XrmClient.ps1:83

I've not been able to determine a root cause to this other than that Microsoft released a new version of their assemblies Microsoft.CrmSdk.CoreTools.9.1.0.115 which appears to be the most likely cause).

Are you able to assist?

**Comment by AymericM78** [comment]
Hello @rtmaus 
I have the same issue with AzureDevops pipelines ...
But not on my laptops (windows).

**Comment by AymericM78** [comment]
@rtmaus 
Issue should be solved now with version 1.0.0.102, can you confirm please?
It work on AzDevops Pipelines :)

**Comment by AymericM78** [comment]
@rtmaus I close this issue but feel free to reopen it if necessary. Thx
