### ISSUE TITLE
Impossible to connect to my Dataverse environment

### ISSUE THREAD

**Issue by JMG74** [AymericM78/PowerDataOps#8]
Hi Aymeric !

I've just discovered your tool which seems very promising as I'm looking to set up data before doing automatic tests.

I've started to test the possibilities of PowerDataOps but I can't connect to my Dataverse environment. Here's the code I've written based on the “documentation/samples/Working with data.md” example in your doc:
```
$url = "https://XXXXX.dynamics.com";
$clientId = "YYYYY";
$clientSecret = "ZZZZZ";
$connectionString = "AuthType=ClientSecret;Url=$url;ClientId=$clientId;ClientSecret=$clientSecret;"
$xrmClient = New-XrmClient -ConnectionString $connectionString;
```
I'm always getting the following error:

> ERROR REQUESTING Token FROM THE Authentication context - General ADAL Error One or more errors occurred. (Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.) Unable to Login to Dynamics CRM

The real values corresponding to XXXXX, YYYYY, ZZZZZ above seems correct because I can connect with them in XrmToolBox and work normally in FetchXML Builder.

My PC is running on Windows 11 x64.

Do you have any idea of what could be my problem ?
Looking forward for your feedback and thanks in advance for your help.

Best regards.

**Comment by JMG74** [comment]
After a few more hours of investigation and testing, I realized that it was my version of PowerShell (7.4.4, ditto for 7.4.5) that was the source of the problem. I went back to version 5.1 and now it's working 👍 !
Do you have any idea why it's not working when using PowerShell v7.4.4 or 7.4.5 ?

**Comment by AymericM78** [comment]
Hello

Thanks for your message !
Sorry about that, my module is only supported on pshell 5.1 but I've
started to work on a new version for v7.
This take time because I need to handle core functions differently and I
have difficulties to find time for this.

If you want to help me, we can share tasks to boost this projet ?

Thanks

**Comment by AymericM78** [comment]
Hello @JMG74 

For your information, version 2 now work on powershell v7

**Comment by JMG74** [comment]
Excellent !! I will give a new try from PowerShell v7.
Thank you !
